databases:
  - name: weatherproject
    databaseName: weatherproject
    user: weatherproject

services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn weatherproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: weatherproject
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 1  # Limited to 1 instance for free tier
