databases:
  - name: weatherdb
    databaseName: weatherproject  # Ensure this matches your Django settings
    user: weatherproject
    password: 'SECRET_KEY'

services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn weatherproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: weatherdb
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 1  # For free instance types, only 1 web concurrency is supported

# Optional: If you need additional environment variables, add them here
